language: android
env:
  global:
    # Issue 69735:	Ddmlib is too agressive with timeouts in Device.java
    # ddmlib is timing out too quickly with the default 2 minute configuration when it doesn't receive input.
    # Considering Travis VM (and potentially the emulator) tends to run slow, we need to up this value
    # as installing an APK can take longer than 2 minutes.  (https://code.google.com/p/android/issues/detail?id=69735)
    #
    # See also:
    #   http://stackoverflow.com/questions/28949722/android-tests-fail-on-travis-with-shellcommandunresponsiveexception/28949723#28949723
    - ADB_INSTALL_TIMEOUT=8 # default is 2 (minutes)

    # HockeyApp APP ID
    - secure: kM462SlC1A3qwOk7iQnloFiZS4Zau5bXmhefcOEztpiGs+/s1zOQ1DL6FzYcGyS2L6JBjO8Msp4To7RcRheQcoWUxhVwDDlrttT++4Psqf8eYHRe5mzQHL99ePTY7OJ+fYM8n1Yl3cjV/2fK3bF8HsuEfATrSuzx7BkiX0usaIWV/+gP7DVJlG/sW2ojsJgSEizHqqr47eD6MIntvDXLCWcQAP/WoekixUO6Lqssu29NTmxq7aYrGExAk//DShKbR2nj5/m5akpkI6FJM8okB6zY6BA23Rph9rFSFHmx0dN8K/3VioFomm4RjZhDWNn+9PeYTcdJLF/XPLFkUZ1YUVyHvmXQ+Bf5+y4ErFMKb/OoJJructf9APXsrmFa+/T4elfgZW9g+A/ILg26qoAFqs7kkgZBA52TPYgii4YNF2M0Zd4DRLiBuYjv+62yqkB6aBQ835Gej0na2LaPoSJMB70hUerQWvbzj0wZcm+qJJ2sYb0D1B19MdoiTHOVzzADVXlBD+WqcIc4TtQvZBYbbrObVzMuha3mk+kA6lmWDAW+rvbjObbEpCyJ4UXJ6dgDU/Y1Hc4aROejR2Dh2HALA8/MV5iaWkH0L05e2Vo1cbeSIXbbO01IQ2NSVcaNTIBZvYyO9t0g4zDdO26lWkiYbG0ESlyGdhBmCbu02APbWAo=
    # HockeyApp Api Token
    - secure: DXp/MQMf/PQNNmks08u75i8Bju/9wSYt7Ci55Szy4d7jrPXDIA4/wpJQpGRqZhBB8j1DGU309yifliGNQi6/0JBhQhn892McxaR1010Ghcmt82f2F0OnYDjPc8NUOk71JA/mhjHiohp1QVBGCA3P3/EFugcFbvyvCK3Iy7HhTdblrE8As5S2iEzaKiUv4FZcBARaelf9lQzABaV5zkfQ7kkXF1YGy3hxL1B7dUH2j7DHPCh+iYg9CQ/rbcBXelwN0js/3L+R58cIrCSx3tZO4Dogomu9AAnTXrsDSZ6D7gvDe6LODW5tHNzhtH8d0TIYdw+/WkV5jiwVqlzAn+zGWBPVc5oIOj8bsT0YSi6smtFaV++M1AEeCg9cZldgCGA/wv3VBbgRsufJ56010PoVP9kzFNChaftkhr2UrlxzO2QedzXMWJVnOWQA6ATFPNxtrHkdKzbph4ul97uASlNXtIFws8NAq1xXN4KthURYGx95mJvjYD0tdMu+ICcMoFZlm7SVa+iqxiqFUY+GjVEfik4o6xx9uSzj0uR33CFrJvWiz8tsLVVB7nNs1Z61gIS7vQt1R8GX/WOIuhYiuOMUD7PypEMMsUW0RgNNLb4yKxy4KeiXxZcd287IkZmAZonrZNM6pldoyftCHSJuxBsG5hZjczYCY+8McL8W1/E0e+c=

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-19.1.0

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-android-support
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-19
    #- sys-img-x86-android-17

    # Emulator Management: Create, Start and Wait
before_script:
  # Create test using image 8 (Nexus 5).  TODO: Device details should probably be set explicitly incase default image IDs somehow change.
  # For more device options: android list devices
  # http://docs.travis-ci.com/user/languages/android/#How-to-Create-and-Start-an-Emulator
  - echo no | android create avd --force -n test -t 8
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

after_success:
  # Upload the generated apk to HockeyApp
  ./scripts/upload_apk.sh
